spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9091, 127.0.0.1:9092, 127.0.0.1:9093
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/coupon_example
    username: root
    password: 1234
