spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9091, 127.0.0.1:9092, 127.0.0.1:9093
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.springframework.kafka.core.KafkaProducer: DEBUG
    org.springframework.kafka.listener.KafkaMessageListenerContainer: DEBUG